Delete Azure Functions
SkillsFundingAgency/das-pensionsregulator pull request #55
Opened 2020-12-17 12:00 UTC by uhimabindu

2020-12-17 12:41 UTC, arvinthseran approved these changes

2021-01-04 12:00 UTC, CodeWolf86 requested changes
The removal of the functions look fine as that's now being replaced by the ADF code that lives in das-data-factory.

Does the ADF implementation still make use of the stored procedures that the function app called? Or is there further simplification that can be done e.g. removing https://github.com/SkillsFundingAgency/das-pensionsregulator/blob/ASINTEL-1274-RemoveGitCodeForAzureFunctions/src/SFA.DAS.PensionsRegulator.Database/StoredProcedures/LoadTPRFile.sql which is called by the `PensionRegulatorRepository` that is being deleted?

2021-01-04 13:53 UTC, CodeWolf86 approved these changes

2021-01-04 13:54 UTC, arvinthseran approved these changes

2021-01-04 14:21 UTC, merged